name: Tests
on: push
jobs:
  linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: bandit
        run: make bandit
      - name: black
        run: make black
      - name: flake8
        run: make flake8
      - name: isort
        run: make isort
