### This is the Terraform-generated stage-build.yml workflow for the                     ###
### dspace-submission-service-stage app repository                                       ###
### If the container requires any additional pre-build commands, uncomment and edit      ###
### the PREBUILD line at the end of the document.                                        ###
name: Stage Container Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Stage Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-stage.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "dspace-submission-service-gha-stage"
      ECR: "dspace-submission-service-stage"
      # PREBUILD: 
